title = ""
baseURL = "https://logan.github.io/scratch"
languageCode = "fr-fr"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-45982985-3"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  facebook = ""
  twitter = "https://twitter.com/LoganMzz"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "http://www.ac-grenoble.fr/ien.chambery4/wp-content/uploads/2016/02/scratchlogo.jpg"
  recent_posts_number = 2
